// Generated by CoffeeScript 1.9.3
(function() {
  var Fraction, ajouter_deux_fractions, multiplier_deux_fractions;

  Fraction = (function() {
    function Fraction(numerateur, denominateur) {
      this.numerateur = numerateur;
      this.denominateur = denominateur;
      if (this.denominateur < 0) {
        this.numerateur *= -1;
        this.denominateur *= -1;
      }
    }

    Fraction.prototype.irreductible = function() {
      var a, b, ref, ref1;
      ref = [this.numerateur, this.denominateur], a = ref[0], b = ref[1];
      while (b !== 0) {
        ref1 = [b, a % b], a = ref1[0], b = ref1[1];
      }
      this.denominateur /= a;
      return this.numerateur /= a;
    };

    Fraction.prototype.inverse = function() {
      var ref;
      return ref = [this.denominateur, this.numerateur], this.numerateur = ref[0], this.denominateur = ref[1], ref;
    };

    Fraction.prototype.oppose = function() {
      return this.numerateur = -this.numerateur;
    };

    return Fraction;

  })();

  ajouter_deux_fractions = function(f1, f2) {
    var d, foo, n;
    n = f1.numerateur * f2.denominateur + f2.numerateur * f1.denominateur;
    d = f1.denominateur * f2.denominateur;
    return foo = new Fraction(n, d);
  };

  multiplier_deux_fractions = function(f1, f2) {
    var d, foo, n;
    n = f1.numerateur * f2.numerateur;
    d = f1.denominateur * f2.denominateur;
    return foo = new Fraction(n, d);
  };

}).call(this);
